### ISSUE TITLE
[Task] USERS DB 스키마 구축

### ISSUE THREAD

**Issue by kihunism** [kihunism/codingdic#5]
### 날짜
2021/ 12/ 29 (수)

### 개발 단
`Backend`

### TODO 리스트 작성
- [x] DB Sequelize 복습/ 구글링
- [x] 'codingdictionary' 데이터베이스 만들고, dotenv, config.js 작성 및 수정하기
- [x] 'users' 테이블 만들고 테스트 하기
