### ISSUE TITLE
[Task] USERS signup 구현

### ISSUE THREAD

**Issue by kihunism** [kihunism/codingdic#6]
### 날짜
2021/ 12/ 29 (수)

### 개발 단
`Backend`

### TODO 리스트 작성
- [ ] 정규식을 통한 유효성 검증
- [ ] 예외처리 및 데이터베이스 중복 검사
- [x] 포스트맨으로 테스트
- [ ] 에러코드 응답 모듈화(나중에 계속 쓰기 위함)
